# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/138fdnDe6aduM9sPpxnbvJGLIH5gtg-96
"""

import streamlit as st
from pypdf import PdfReader
from sentence_transformers import SentenceTransformer
import numpy as np
from langchain_community.vectorstores import FAISS
from langchain_text_splitters import RecursiveCharacterTextSplitter
from groq import Groq


# --------------------------
# Load Groq API Key
# --------------------------
groq_api_key = st.secrets["GROQ_API_KEY"]
client = Groq(api_key=groq_api_key)


# --------------------------
# Function to Query LLM
# --------------------------
def get_llm_answer(question, context):
    prompt = f"""
    You are an expert on the Indian Constitution.
    Use the following context to answer the question.

    CONTEXT:
    {context}

    QUESTION:
    {question}

    ANSWER:
    """

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}]
    )

    # NEW Groq format → message.content is a list of objects
    return response.choices[0].message.content[0].text


# --------------------------
# Create Vector DB From PDF
# --------------------------
@st.cache_resource
def load_vector_db(pdf_file):

    reader = PdfReader(pdf_file)
    text = ""

    for page in reader.pages:
        extracted = page.extract_text()
        if extracted:
            text += extracted

    # Split PDF text
    splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=150)
    chunks = splitter.split_text(text)

    # Load embedding model
    model = SentenceTransformer("all-MiniLM-L6-v2")
    embeddings = model.encode(chunks)

    # Convert embeddings to list of numpy arrays
    embeddings = [np.array(e) for e in embeddings]

    # Build FAISS DB
    db = FAISS.from_embeddings(list(zip(chunks, embeddings)))

    return db, chunks


# --------------------------
# Streamlit UI
# --------------------------
st.title("📘 Indian Constitution QA ")

uploaded_pdf = st.file_uploader("Upload Constitution PDF", type=["pdf"])

if uploaded_pdf:
    st.success("PDF loaded! Creating Vector Store… (1st time only)")
    vectordb, chunks = load_vector_db(uploaded_pdf)

    question = st.text_input("Ask any question about the Constitution:")

    if question:
        docs = vectordb.similarity_search(question, k=6)
        context = "\n\n".join([d.page_content for d in docs])

        st.write("### 📌 Answer:")
        answer = get_llm_answer(question, context)
        st.write(answer)
